# Generated by Django 4.2.13 on 2024-07-08 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('nb_place', models.IntegerField()),
                ('type_table', models.CharField(choices=[('VIP', 'VIP'), ('Simple', 'Simple'), ('Familiale', 'Familiale')], max_length=50)),
                ('statut', models.CharField(choices=[('Occupé', 'Occupé'), ('Non occupé', 'Non occupé')], default='Non occupé', max_length=50)),
                ('nb_chaises', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
    ]
