# Generated by Django 4.2.13 on 2024-07-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_table_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
