# Generated by Django 4.2.13 on 2024-07-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='nb_chaises',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='nb_place',
            field=models.IntegerField(default=0),
        ),
    ]
