# Generated by Django 4.2.13 on 2024-07-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantOwner',
        ),
    ]
